hook.Add("CloudMusicCreatePage", "CloudMusicMainPage", function(frame)
    local page = frame:AddPage("Main")
    function page:Paint()
        draw.DrawText("This is main page","CloudMusicText",0,0,Color(0,0,0))
    end
    local sBtn = CloudMusic.UI.CreateVGUI("CloudMusicButton", page)
    sBtn:SetPos(0, 20)
    sBtn:SetText("换页")
    function sBtn:DoClick()
        frame:SwitchPage("Settings")
    end
    local sBtn = CloudMusic.UI.CreateVGUI("CloudMusicButton", page)
    sBtn:SetPos(0, 50)
    sBtn:SetText("提示")
    function sBtn:DoClick()
        frame:ShowMessage("nmsl","我把你妈杀了")
        frame:ShowMessage("操你妈","你是不是憨批啊",CM_MSG_ERR,5)
        frame:ShowMessage("以下内容要求全文背诵","盼望着，盼望着，东风来了，春天的脚步近了。 一切都像刚睡醒的样子，欣欣然张开了眼。山朗润起来了，水涨起来了，太阳的脸红起来了。",CM_MSG_SUCCESS,6)
    end
end)